solver:
  t: 100
  dt: 0.01
  theta: 0.5
generator:
  count: 2500
  # Masses are distributed according to power law
  min_mass: 0.08
  max_mass: 100.0
  power_mass: 2.35
  scale_mass: 0.01
  # Distances are distributed according exponential law
  max_distance: 4.0
  min_velocity: 0.0
  max_velocity: 0.0
