solver:
  t: 3.14
  dt: 0.001
  theta: 0.5
  # Optimal smoothing length is 1.1 * count ** -0.28
  epsilon: 0.08
generator:
  count: 10000
  # Parameters of a Plummer model
  # M = -4E = G = 1
  # Aarseth, SJ, Henon, M, & Wielen, R (1974) Astr & Ap, 37, 183.
  scale_factor: 0.589
frontend:
  enable: true
  refresh_every: 1
output:
  enable: true
