solver:
  t: 6.28
  dt: 0.01
  theta: 1.0
  epsilon: 1.0
generator:
  count: 10000
  # Masses are distributed according to power law
  min_mass: 1.0
  max_mass: 2.0
  power_mass: 2.38
  scale_mass: 1.0
  # Distances distributed uniformly
  max_distance: 100.0
  # Distances distributed uniformly
  scale_velocity: 0.5
frontend:
  enable: true
  refresh_every: 2
output:
  enable: true
